import type { FrameworkDefinition } from "./types";

export const proppsFunctions: FrameworkDefinition = {
  id: "propps-functions",
  name: "Propp's Functions",
  color: "#22c55e",
  beats: [
    {
      name: "Absentation",
      description: "A family member leaves home, dies, or is otherwise absent — creating vulnerability and setting the story in motion.",
      examples: ["A parent dies or goes on a journey", "A child is left alone or unsupervised", "The protector of the community departs"],
      startPercent: 0, endPercent: 3,
    },
    {
      name: "Interdiction",
      description: "A warning or prohibition is given to the hero — 'don't go into the forest,' 'don't open the box.'",
      examples: ["'Don't leave the path' in fairy tales", "'Never feed them after midnight' in Gremlins", "'Don't open Pandora's box'"],
      startPercent: 3, endPercent: 6,
    },
    {
      name: "Violation",
      description: "The interdiction is broken — the hero or another character does exactly what they were told not to do.",
      examples: ["Red Riding Hood strays from the path", "Pandora opens the box", "The characters feed the mogwai after midnight"],
      startPercent: 6, endPercent: 9,
    },
    {
      name: "Reconnaissance",
      description: "The villain makes an effort to gather information — spying on the hero or their family.",
      examples: ["The wolf asks Red Riding Hood where she's going", "A spy reports back to the evil queen", "The villain sends scouts or disguised agents"],
      startPercent: 9, endPercent: 12,
    },
    {
      name: "Delivery",
      description: "The villain successfully obtains information about the hero or their vulnerabilities.",
      examples: ["The wolf learns where grandmother lives", "The villain discovers the hero's weakness", "A traitor reveals the hero's location"],
      startPercent: 12, endPercent: 14,
    },
    {
      name: "Trickery",
      description: "The villain attempts to deceive the victim — using disguise, false promises, or manipulation.",
      examples: ["The wolf disguises as grandmother", "The witch offers Snow White a poisoned apple", "The villain poses as an ally or friend"],
      startPercent: 14, endPercent: 17,
    },
    {
      name: "Complicity",
      description: "The victim falls for the deception and unknowingly helps the villain or puts themselves in danger.",
      examples: ["Red Riding Hood trusts the disguised wolf", "Snow White eats the apple", "The hero accepts the villain's 'gift'"],
      startPercent: 17, endPercent: 20,
    },
    {
      name: "Villainy / Lack",
      description: "The villain causes direct harm (kidnapping, theft, destruction) OR the hero discovers something is missing or needed.",
      examples: ["A princess is kidnapped by a dragon", "A magical object is stolen", "The kingdom suffers from a curse or famine"],
      startPercent: 20, endPercent: 24,
    },
    {
      name: "Mediation",
      description: "The hero learns of the villainy or lack — they receive a call for help, discover the problem, or are sent on a mission.",
      examples: ["A messenger brings news of the kidnapping", "The hero witnesses the destruction firsthand", "A royal decree calls for a champion"],
      startPercent: 24, endPercent: 27,
    },
    {
      name: "Counteraction",
      description: "The hero decides to act — they accept the quest, vow revenge, or commit to solving the problem.",
      examples: ["The youngest son sets out to rescue the princess", "The hero swears to defeat the dragon", "A volunteer steps forward to answer the call"],
      startPercent: 27, endPercent: 30,
    },
    {
      name: "Departure",
      description: "The hero physically leaves home and begins the journey into the unknown.",
      examples: ["Setting out into the enchanted forest", "Boarding a ship for distant lands", "Crossing the border of the familiar world"],
      startPercent: 30, endPercent: 33,
    },
    {
      name: "First Donor Function",
      description: "The hero encounters a magical helper or donor who tests them — through riddles, tasks, combat, or acts of kindness.",
      examples: ["An old woman asks for food and the hero shares their last bread", "A mystical creature poses three riddles", "The hero must complete a task to prove their worth"],
      startPercent: 33, endPercent: 37,
    },
    {
      name: "Hero's Reaction",
      description: "The hero responds to the donor's test — their reaction determines whether they receive help.",
      examples: ["The hero shows kindness and passes the test", "The hero solves the riddle through cleverness", "The hero fails but shows courage, earning partial aid"],
      startPercent: 37, endPercent: 40,
    },
    {
      name: "Receipt of Agent",
      description: "The hero acquires a magical object, weapon, animal companion, or special knowledge from the donor.",
      examples: ["A magic sword, cloak of invisibility, or enchanted ring", "A loyal animal companion (horse, eagle, wolf)", "Secret knowledge — a spell, map, or weakness of the villain"],
      startPercent: 40, endPercent: 43,
    },
    {
      name: "Guidance",
      description: "The hero is led or directed to the location of the object of their search.",
      examples: ["A magical bird leads the way through the forest", "A map reveals the path to the dragon's lair", "A wise character gives directions to the enchanted castle"],
      startPercent: 43, endPercent: 47,
    },
    {
      name: "Struggle",
      description: "The hero and villain engage in direct combat or confrontation — the central battle of the story.",
      examples: ["A sword fight with the dragon", "A battle of wits with the sorcerer", "A chase through the villain's stronghold"],
      startPercent: 47, endPercent: 53,
    },
    {
      name: "Branding",
      description: "The hero is marked — they receive a wound, scar, ring, or token that identifies them.",
      examples: ["Harry Potter's lightning bolt scar", "A wound from the villain that becomes a badge of honor", "A ring or token given during the battle"],
      startPercent: 53, endPercent: 55,
    },
    {
      name: "Victory",
      description: "The villain is defeated — killed, banished, outsmarted, or otherwise overcome.",
      examples: ["The dragon is slain", "The sorcerer's power is broken", "The evil king is overthrown"],
      startPercent: 55, endPercent: 58,
    },
    {
      name: "Liquidation",
      description: "The initial misfortune or lack is resolved — the kidnapped person is freed, the stolen object recovered, the curse lifted.",
      examples: ["The princess is rescued", "The stolen treasure is returned", "The curse over the kingdom is broken"],
      startPercent: 58, endPercent: 62,
    },
    {
      name: "Return",
      description: "The hero begins the journey home, often by the same route or through new territory.",
      examples: ["Riding home with the rescued princess", "Sailing back with the treasure", "Walking back through the now-peaceful forest"],
      startPercent: 62, endPercent: 66,
    },
    {
      name: "Pursuit",
      description: "The hero is chased — the villain or their allies pursue the hero during the return journey.",
      examples: ["The dragon's minions chase the hero through the mountains", "The villain's spirit pursues in the form of a storm", "Soldiers are sent after the escaping hero"],
      startPercent: 66, endPercent: 70,
    },
    {
      name: "Rescue",
      description: "The hero is saved from pursuit — by hiding, a clever ruse, magical intervention, or an ally's help.",
      examples: ["A river spirit carries the hero to safety", "The hero uses the magic cloak to become invisible", "An ally blocks the pursuers at a bridge"],
      startPercent: 70, endPercent: 73,
    },
    {
      name: "Unrecognized Arrival",
      description: "The hero arrives home or at court but is not recognized — they may be in disguise or changed by the journey.",
      examples: ["Odysseus returns to Ithaca disguised as a beggar", "The hero arrives in humble clothes, unrecognized by the court", "The hero's appearance has changed so much no one knows them"],
      startPercent: 73, endPercent: 76,
    },
    {
      name: "Unfounded Claims",
      description: "A false hero (impostor) claims credit for the hero's deeds — presenting themselves as the one who slew the dragon or rescued the princess.",
      examples: ["A cowardly knight claims he killed the dragon", "An older brother takes credit for the youngest's deeds", "A servant presents the stolen treasure as their own conquest"],
      startPercent: 76, endPercent: 79,
    },
    {
      name: "Difficult Task",
      description: "A final test is proposed — often by the king or princess — to determine the true hero.",
      examples: ["'Only the true hero can string this bow'", "A riddle only the real hero can answer", "A task requiring the magical item only the true hero possesses"],
      startPercent: 79, endPercent: 83,
    },
    {
      name: "Solution",
      description: "The hero completes the difficult task, proving their identity and worth.",
      examples: ["The hero strings the bow and hits the target", "The hero produces the dragon's tooth as proof", "The hero uses the magic ring to reveal the truth"],
      startPercent: 83, endPercent: 87,
    },
    {
      name: "Recognition",
      description: "The hero is finally recognized — by their brand/mark, the magical item, or by completing the task.",
      examples: ["The scar or token identifies the true hero", "The princess recognizes the hero's ring", "The community sees the hero for who they truly are"],
      startPercent: 87, endPercent: 90,
    },
    {
      name: "Exposure",
      description: "The false hero or remaining villain is unmasked and exposed for their deception.",
      examples: ["The impostor cannot complete the task and is revealed", "Evidence proves the false hero lied", "The villain's disguise fails at the crucial moment"],
      startPercent: 90, endPercent: 93,
    },
    {
      name: "Transfiguration",
      description: "The hero is transformed — given new clothes, a new appearance, or elevated status befitting their true nature.",
      examples: ["The ragged hero is given royal garments", "The hero's true beauty is revealed", "A magical transformation marks the hero's ascension"],
      startPercent: 93, endPercent: 95,
    },
    {
      name: "Punishment",
      description: "The villain and/or false hero receive their just punishment.",
      examples: ["The evil stepmother is banished", "The false hero is imprisoned", "The villain meets a poetic end related to their crimes"],
      startPercent: 95, endPercent: 97,
    },
    {
      name: "Wedding",
      description: "The hero is rewarded — typically through marriage to the princess/prince, coronation, or receiving half the kingdom.",
      examples: ["The hero marries the princess and becomes king", "The hero is crowned ruler of the land", "A great celebration marks the hero's triumph and new life"],
      startPercent: 97, endPercent: 100,
    },
  ],
};
